/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * SPDX-License-Identifier: MulanPSL-2.0
 */

#pragma once

enum CuckooCode {
    CUCKOO_SUCCESS = 0,

    CUCKOO_ERR_INVALID_PARAM,
    CUCKOO_ERR_UNSUPPORTED,
    CUCKOO_ERR_FULL,
    CUCKOO_ERR_BUSY,
    CUCKOO_ERR_OBJ_LEN_EXCEED,

    CUCKOO_ERR_OBJ_NOT_EXISTS,
    CUCKOO_ERR_OBS_INVALID_ARG,
    CUCKOO_ERR_OBS_DENY,
    CUCKOO_ERR_OBS_INSUFFICIENT,

    CUCKOO_ERR_INNER_FAILED
};

enum CuckooInnerErrorCode {
    OK = 0,

    CUCKOO_IEC_MALLOC_FAILED = 1000,
    CUCKOO_IEC_INIT_FTDS_FAILED,
    CUCKOO_IEC_INIT_OBS_FAILED,
    CUCKOO_IEC_INIT_LOG_FAILED,
    CUCKOO_IEC_INIT_CONF_FAILED,
    CUCKOO_IEC_INIT_THREAD_POOL_FAILED,
    CUCKOO_IEC_NEED_RETRY,

    CUCKOO_IEC_KV_READ_FAILED = 1100,
    CUCKOO_IEC_KV_NEXT_FAILED,
    CUCKOO_IEC_KV_HAS_NEXT_FAILED,
    CUCKOO_IEC_KV_WRITE_FAILED,
    CUCKOO_IEC_KV_SEAL_FAILED,
    CUCKOO_IEC_KV_APPEND_FAILED,
    CUCKOO_IEC_KV_DELETE_FAILED,
    CUCKOO_IEC_KV_MMAP_FAILED,

    CUCKOO_IEC_KV_FAILED_BUSY = 1200,
    CUCKOO_IEC_KV_FAILED_SEAL,
    CUCKOO_IEC_KV_FAILED_CONFLICT,
    CUCKOO_IEC_KV_FAILED_KEY_NOT_EXIST,

    CUCKOO_IEC_OBS_GET_FAILED = 1300, // TOFO: in original video all "FAILED" in this trunk are mistyped to "FAIELD"
    CUCKOO_IEC_OBS_FAILED_BUSY,
    CUCKOO_IEC_OBS_FAILED_INVALID_ARG,
    CUCKOO_IEC_OBS_FAILED_KEY_NOT_EXIST,
    CUCKOO_IEC_OBS_FAILED_DENY,
    CUCKOO_IEC_OBS_FAILED_INSUFFICIENT,

    CUCKOO_IEC_GRPC_SEND_FAILED = 1400,
    CUCKOO_IEC_GRPC_NO_CLIENT,

    CUCKOO_IEC_DAEMON_EXEC_FAILED = 1500,

    CUCKOO_IEC_UNKNOWN_ERROR = 9999
};
